 
export const locations = [
    {
      id: 1,
      name: "New York City",
      address: "New York, NY, USA",
      latitude: 40.7128,
      longitude: -74.006,
      city: "New York",
      state: "New York",
      country: "United States",
    },
    {
      id: 2,
      name: "Los Angeles",
      address: "Los Angeles, CA, USA",
      latitude: 34.0522,
      longitude: -118.2437,
      city: "Los Angeles",
      state: "California",
      country: "United States",
    },
    {
      id: 3,
      name: "London",
      address: "London, UK",
      latitude: 51.5074,
      longitude: -0.1278,
      city: "London",
      country: "United Kingdom",
    },
    {
      id: 4,
      name: "Paris",
      address: "Paris, France",
      latitude: 48.8566,
      longitude: 2.3522,
      city: "Paris",
      country: "France",
    },
    {
      id: 5,
      name: "Tokyo",
      address: "Tokyo, Japan",
      latitude: 35.6895,
      longitude: 139.6917,
      city: "Tokyo",
      country: "Japan",
    },
  ];